production:
  :facebook:
    :app_id: '189879571063723'
    :app_secret: '4d86565c2e66cfb66d8abded500cc4f8'
  :twitter:
    :consumer_key: 'yABWbIRA0s0s1Jc81B8Dg'
    :consumer_secret: 'IuboXnkpR7HFXm4S60WBYCxQyvr41KWE0DNYFQmGU5s'
  :linked_in:
    :app_key: 'vpxxq9lfgeqj'
    :app_secret: 'VROhTv0A0FpV7wCl'
development:
  :facebook:
    :app_id: '627711beba2da431d2266bfe40c41618'
    :app_secret: 'e042af88df1ec657121d3609e353740a'
  :twitter:
    :consumer_key: 'ECY3RkpRtk7sNIa9OtELQ'
    :consumer_secret: 'X9oIRrQ9GSfQxKre7MmOM8gpoEx8dDOfZkX5paAQ'
  :linked_in:
    :app_key: 'vpxxq9lfgeqj'
    :app_secret: 'VROhTv0A0FpV7wCl'